### ISSUE TITLE
繁體字

### ISSUE THREAD

**Issue by tigerninjaman** [stopwords-iso/stopwords-zh#3]
有繁體的嗎?我不要自己翻譯...

**Comment by Hausekey** [comment]
Hi tigerninjaman, 
I had a similar issue. Have you considered using a 简化字 -> 繁體 converter tool?
I found https://www.purpleculture.net/traditional-simplified-converter/ online tool to help.

**Comment by genediazjr** [comment]
currently no support for traditional. I'm open to accepting pr.
